# https://skaffold.dev/docs/tutorials/ci_cd/
steps:
- name: 'gcr.io/k8s-skaffold/skaffold:latest'
  id: Deploy to Staging Cluster
  args:
  - 'run'
  - '--default-repo'
  - 'gcr.io/${PROJECT_ID}/cymbal-bank/${BRANCH_NAME}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cymbal-staging'